//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarSharing.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Auto
    {
        public int AutoId { get; set; }
        public int FarbId { get; set; }
        public int MarkeId { get; set; }
        public int ModellId { get; set; }
        public int KennzeichenNummerId { get; set; }
        public int TypId { get; set; }
        public int GetriebartId { get; set; }
        public int TreibstoffId { get; set; }
        public int AntriebId { get; set; }
        public Nullable<int> Kilometer { get; set; }
    
        public virtual Antrieb Antrieb { get; set; }
        public virtual Farbe Farbe { get; set; }
        public virtual Getriebeart Getriebeart { get; set; }
        public virtual KennzeichenNummer KennzeichenNummer { get; set; }
        public virtual Marke Marke { get; set; }
        public virtual modell modell { get; set; }
        public virtual Treibstoff Treibstoff { get; set; }
        public virtual Typ Typ { get; set; }
    }
}
